telegram:
  about: Soy Donna Auchaway. Mis pronombres son neutros (elle) y soy le cyborg de Auch!
  commands: |
    start - Hola Donna!
    about - Contame de vos
    contame_de - Contame algo de...
    pronombres - Mis pronombres son...
    chats_privados - Mis preferencias sobre chats privados son...
    stop - Chau Donna!
  description: |
    Hola, soy Donna. Mis pronombres son neutros (elle) y soy le cyborg de Auch!
    
    Puedo recordar tus pronombres y preferencias sobre si te pueden escribir
    otrxs miembrxs del grupo, así cualquiera puede preguntarme antes de
    interactuar con vos. También podés preguntarme por quien quieras!
  group: donna_test
